# Paste this entire file into ONE notebook cell, then Shift+Enter
import os, zipfile

base = "/mnt/workspace/neuroplc-paper"
for d in ["code/models","code/neuroplc/utils","code/tests","data/processed","data/splits","results/teacher","results/student","results/scl_output","results/figures","paper"]:
    os.makedirs(base + "/" + d, exist_ok=True)

# === student_mlp.py ===
with open(base + "/code/models/student_mlp.py", "w") as f:
    f.write("import torch\nimport torch.nn as nn\n")
    f.write("class StudentMLP(nn.Module):\n")
    f.write(" def __init__(self,input_dim=28,hidden_dims=None,num_classes=4,dropout=0.1):\n")
    f.write("  super().__init__()\n")
    f.write("  if hidden_dims is None: hidden_dims=[32,16]\n")
    f.write("  layers=[]; d=input_dim\n")
    f.write("  for h in hidden_dims:\n")
    f.write("   layers+=[nn.Linear(d,h),nn.ReLU(),nn.Dropout(dropout)]\n")
    f.write("   d=h\n")
    f.write("  layers.append(nn.Linear(d,num_classes))\n")
    f.write("  self.net=nn.Sequential(*layers)\n")
    f.write("  for m in self.modules():\n")
    f.write("   if isinstance(m,nn.Linear):\n")
    f.write("    nn.init.kaiming_uniform_(m.weight,nonlinearity='relu')\n")
    f.write("    nn.init.zeros_(m.bias)\n")
    f.write(" def forward(self,x): return self.net(x)\n")
print("1: student_mlp.py OK")

# === teacher_cnn.py ===
with open(base + "/code/models/teacher_cnn.py", "w") as f:
    f.write("import torch\nimport torch.nn as nn\nimport torch.nn.functional as F\n")
    f.write("class SelfAttention1D(nn.Module):\n")
    f.write(" def __init__(self,dim,heads=4,dropout=0.1):\n")
    f.write("  super().__init__(); self.dim,self.heads=dim,heads\n")
    f.write("  self.head_dim=dim//heads; self.scale=self.head_dim**-0.5\n")
    f.write("  self.qkv=nn.Linear(dim,dim*3,bias=False)\n")
    f.write("  self.proj=nn.Linear(dim,dim); self.dropout=nn.Dropout(dropout)\n")
    f.write(" def forward(self,x):\n")
    f.write("  B,C,L=x.shape; x_t=x.transpose(1,2)\n")
    f.write("  qkv=self.qkv(x_t).reshape(B,L,3,self.heads,self.head_dim).permute(2,0,3,1,4)\n")
    f.write("  q,k,v=qkv[0],qkv[1],qkv[2]\n")
    f.write("  attn=(q@k.transpose(-2,-1))*self.scale\n")
    f.write("  attn=F.softmax(attn,dim=-1); attn=self.dropout(attn)\n")
    f.write("  out=(attn@v).transpose(1,2).reshape(B,L,C)\n")
    f.write("  return self.proj(out).transpose(1,2)\n")
    f.write("class ConvBlock(nn.Module):\n")
    f.write(" def __init__(self,ic,oc,k,p):\n")
    f.write("  super().__init__(); self.conv=nn.Conv1d(ic,oc,k,padding=k//2)\n")
    f.write("  self.bn=nn.BatchNorm1d(oc); self.pool=nn.MaxPool1d(p)\n")
    f.write(" def forward(self,x): return self.pool(F.relu(self.bn(self.conv(x))))\n")
    f.write("class TeacherCNN(nn.Module):\n")
    f.write(" def __init__(self,num_classes=4):\n")
    f.write("  super().__init__()\n")
    f.write("  self.cb=nn.ModuleList([ConvBlock(1,16,15,4),ConvBlock(16,32,9,2),ConvBlock(32,64,5,2)])\n")
    f.write("  self.attn=SelfAttention1D(64,4,0.3); self.ap=nn.AdaptiveAvgPool1d(1)\n")
    f.write("  self.clf=nn.Sequential(nn.Linear(64,128),nn.ReLU(),nn.Dropout(0.3),nn.Linear(128,64),nn.ReLU(),nn.Dropout(0.3),nn.Linear(64,num_classes))\n")
    f.write("  for m in self.modules():\n")
    f.write("   if isinstance(m,nn.Conv1d): nn.init.kaiming_normal_(m.weight,mode='fan_out',nonlinearity='relu')\n")
    f.write("   elif isinstance(m,nn.Linear):\n")
    f.write("    nn.init.kaiming_uniform_(m.weight,nonlinearity='relu')\n")
    f.write("    if m.bias is not None: nn.init.zeros_(m.bias)\n")
    f.write(" def forward(self,x,rf=False):\n")
    f.write("  for c in self.cb: x=c(x)\n")
    f.write("  x=self.attn(x); x=self.ap(x).squeeze(-1); feats=x; x=self.clf(x)\n")
    f.write("  return (x,feats) if rf else x\n")
    f.write(" def get_features(self,x):\n")
    f.write("  for c in self.cb: x=c(x)\n")
    f.write("  x=self.attn(x); return self.ap(x).squeeze(-1)\n")
    f.write(" @property\n")
    f.write(" def parameter_count(self): return sum(p.numel() for p in self.parameters() if p.requires_grad)\n")
print("2: teacher_cnn.py OK")

print("ALL DONE — 2 model files created")
print("Missing: student_kan.py (B-spline KAN — too long for this script)")
print("Next: drag the real student_kan.py from your local D:\\neuroplc-paper\\code\\models\\")
