#!/usr/bin/env python3
"""Export all 5 Origin figures properly."""
import os, time, win32com.client

OUT = r"D:\neuroplc-paper\paper\figures"
os.makedirs(OUT, exist_ok=True)

o = win32com.client.Dispatch("Origin.ApplicationSI")
print("Connected to Origin")

# === Figure 1: C^2-BV grouped bar ===
o.Execute("doc -n;")
o.Execute("wks.ncols = 4;")
o.Execute(r'wks.col1.label$ = "Architecture";')
o.Execute(r'wks.col2.label$ = "Z3 Rate (%)";')
o.Execute(r'wks.col3.label$ = "CWRU Acc (%)";')
o.Execute(r'wks.col4.label$ = "Safety Margin";')
o.Execute("wks.col1.text$ = B-spline KAN;")
o.Execute("wks.col2.cell1$ = 100; wks.col3.cell1$ = 99.93; wks.col4.cell1$ = 4.5;")
o.Execute("wks.col2.cell2$ = 100; wks.col3.cell2$ = 100;  wks.col4.cell2$ = 2.9;")
o.Execute("wks.col2.cell3$ = 100; wks.col3.cell3$ = 100;  wks.col4.cell3$ = 5.6;")
o.Execute("wks.col2.cell4$ = 96.9; wks.col3.cell4$ = 99.87; wks.col4.cell4$ = 1.1;")
o.Execute("wks.col2.cell5$ = 0;   wks.col3.cell5$ = 24.13; wks.col4.cell5$ = 0;")
o.Execute("plotgroup iy:=(1,3) plot:=200 type:=1; page.title=0;")
o.Execute(r'layer.x.label.text$ = "C\+ (2)-BV Architecture";')
o.Execute(r'layer.y.label.text$ = "Value";')
o.Execute("label -r legend;")
o.Execute(f'expGraph type:=pdf filename:="{OUT}\\fig_c2bv_origin.pdf" tr:=origin;')
o.Execute(f'expGraph type:=png filename:="{OUT}\\fig_c2bv_origin.png" width:=1200 tr:=origin;')
print("  [1/5] C2BV done")
time.sleep(1)

# === Figure 2: DA vs IA grouped bar ===
o.Execute("doc -n;")
o.Execute("wks.ncols = 3;")
o.Execute(r'wks.col1.label$ = "N"; wks.col2.label$ = "DA"; wks.col3.label$ = "IA";')
o.Execute("wks.col1.SetData([8,10,12,15,18,20], 0);")
o.Execute("wks.col2.SetData([0.419,0.305,0.212,0.079,0.055,0.044], 0);")
o.Execute("wks.col3.SetData([0.922,0.671,0.466,0.172,0.121,0.097], 0);")
o.Execute("plotgroup iy:=(1,2) plot:=200 type:=1; page.title=0;")
o.Execute(r'layer.x.label.text$ = "LUT Points N"; layer.y.label.text$ = "Error Bound";')
o.Execute(f'expGraph type:=pdf filename:="{OUT}\\fig_da_vs_ia_origin.pdf" tr:=origin;')
o.Execute(f'expGraph type:=png filename:="{OUT}\\fig_da_vs_ia_origin.png" width:=1200 tr:=origin;')
print("  [2/5] DA vs IA done")
time.sleep(1)

# === Figure 3: Model params+acc ===
o.Execute("doc -n;")
o.Execute("wks.ncols = 3;")
o.Execute(r'wks.col1.label$ = "Model"; wks.col2.label$ = "Params"; wks.col3.label$ = "Acc (%)";')
o.Execute("wks.col1.text$ = Teacher; wks.col2.cell1$ = 48708; wks.col3.cell1$ = 99.93;")
o.Execute("wks.col2.cell2$ = 6148; wks.col3.cell2$ = 99.93;")
o.Execute("wks.col2.cell3$ = 6676; wks.col3.cell3$ = 100;")
o.Execute("wks.col2.cell4$ = 4628; wks.col3.cell4$ = 100;")
o.Execute("wks.col2.cell5$ = 6400; wks.col3.cell5$ = 99.87;")
o.Execute("wks.col2.cell6$ = 1524; wks.col3.cell6$ = 99.89;")
o.Execute("plotgroup iy:=(1,2) plot:=200 type:=1; page.title=0;")
o.Execute(r'layer.x.label.text$ = "Model"; layer.y.label.text$ = "Value";')
o.Execute(f'expGraph type:=pdf filename:="{OUT}\\fig_models_origin.pdf" tr:=origin;')
o.Execute(f'expGraph type:=png filename:="{OUT}\\fig_models_origin.png" width:=1200 tr:=origin;')
print("  [3/5] Models done")
time.sleep(1)

# === Figure 4: Cross-domain transfer ===
o.Execute("doc -n;")
o.Execute("wks.ncols = 4;")
o.Execute(r'wks.col1.label$ = "Arch"; wks.col2.label$ = "CWRU"; wks.col3.label$ = "XJTU-SY"; wks.col4.label$ = "Z3 Rate";')
o.Execute("wks.col1.text$ = B-spline; wks.col2.cell1$ = 99.93; wks.col3.cell1$ = 91.7; wks.col4.cell1$ = 100;")
o.Execute("wks.col2.cell2$ = 100; wks.col3.cell2$ = 100; wks.col4.cell2$ = 100;")
o.Execute("wks.col2.cell3$ = 100; wks.col3.cell3$ = 100; wks.col4.cell3$ = 100;")
o.Execute("wks.col2.cell4$ = 99.87; wks.col3.cell4$ = 0; wks.col4.cell4$ = 96.9;")
o.Execute("wks.col2.cell5$ = 24.13; wks.col3.cell5$ = 0; wks.col4.cell5$ = 0;")
o.Execute("plotgroup iy:=(1,3) plot:=200 type:=1; page.title=0;")
o.Execute(r'layer.x.label.text$ = "Architecture"; layer.y.label.text$ = "Value (%)";')
o.Execute(f'expGraph type:=pdf filename:="{OUT}\\fig_cross_domain_origin.pdf" tr:=origin;')
o.Execute(f'expGraph type:=png filename:="{OUT}\\fig_cross_domain_origin.png" width:=1200 tr:=origin;')
print("  [4/5] Cross-domain done")
time.sleep(1)

# === Figure 5: WCET pie ===
o.Execute("doc -n;")
o.Execute("wks.ncols = 2;")
o.Execute(r'wks.col1.label$ = "Component"; wks.col2.label$ = "Time (ms)";')
o.Execute("wks.col1.text$ = LUT L0 (448 edges); wks.col2.cell1$ = 16.44;")
o.Execute("wks.col2.cell2$ = 2.35;")
o.Execute("wks.col2.cell3$ = 3.70;")
o.Execute("wks.col2.cell4$ = 0.11;")
o.Execute("wks.col2.cell5$ = 0.07;")
o.Execute("plotxy iy:=[%H]1!(1,2) plot:=200 ogl:=1; page.title=0;")
o.Execute(r'layer.y.label.text$ = "Time (ms)"; layer.x.label.text$ = "Component";')
o.Execute(f'expGraph type:=pdf filename:="{OUT}\\fig_wcet_origin.pdf" tr:=origin;')
o.Execute(f'expGraph type:=png filename:="{OUT}\\fig_wcet_origin.png" width:=1200 tr:=origin;')
print("  [5/5] WCET done")

print(f"\nAll 5 Origin figures exported to {OUT}")
